module.exports = {
  main: {
    'Getting Started': ['welcome'],
    Guides: [
      'guides/diagram-editor',
      'keyboard-shortcuts',
      'gdb-debugging',
      'guides/serial-monitor',
      'guides/logic-analyzer',
      'guides/libraries',
      'guides/micropython',
    ],
    'Diagram Reference': [
      'diagram-format',
      'parts/wokwi-74hc595',
      'parts/wokwi-7segment',
      'parts/wokwi-analog-joystick',
      'parts/wokwi-arduino-mega',
      'parts/wokwi-arduino-nano',
      'parts/wokwi-arduino-uno',
      'parts/wokwi-attiny85',
      'parts/wokwi-buzzer',
      'parts/wokwi-dht22',
      'parts/wokwi-ds1307',
      'parts/wokwi-franzininho',
      'parts/wokwi-ir-receiver',
      'parts/wokwi-ir-remote',
      'parts/wokwi-lcd1602',
      'parts/wokwi-lcd2004',
      'parts/wokwi-led',
      'parts/wokwi-logic-analyzer',
      'parts/wokwi-membrane-keypad',
      'parts/wokwi-nano-rp2040-connect',
      'parts/wokwi-ntc-temperature-sensor',
      'parts/wokwi-pi-pico',
      'parts/wokwi-pir-motion-sensor',
      'parts/wokwi-potentiometer',
      'parts/wokwi-pushbutton',
      'parts/wokwi-resistor',
      'parts/wokwi-servo',
      'parts/wokwi-slide-potentiometer',
      'parts/wokwi-slide-switch',
      'parts/wokwi-ssd1306',
    ],
  },
};
